services:
  metronome:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - './project:/usr/src/app/project'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      